### ISSUE TITLE
my Outbound queue is not up kindly help

### ISSUE THREAD

**Issue by omiozil** [fdanismaz/java#3]
My input queue is up but my output queue is not up....so data is pending in intput queue

**Comment by omiozil** [comment]
okay my Outbound queue is also up but i am not able to make sure whether my inbound queue is consuming the data.

**Comment by fdanismaz** [comment]
That sample project is supposed to get data from the input queue, convert it and write it to the output queue. Simply your input queue receives the message you sent, and your output queue should contain the converted message. You can monitor your queues from the administration UI of your ActiveMQ.
